### ISSUE TITLE
Exits with error when running on Proxmox 8

### ISSUE THREAD

**Issue by Jarige** [simoncaron/ansible-role-pve_acme#3]
I'm getting the following error when running this on Proxmox 8:

TASK [simoncaron.pve_acme : Install pexpect] ****************************************************************************************************************************************************************************************************************************
fatal: [proxmox1]: FAILED! => {"changed": false, "cmd": ["/usr/bin/python3", "-m", "pip.__main__", "install", "pexpect"], "msg": "\n:stderr: error: externally-managed-environment\n\n× This environment is externally managed\n╰─> To install Python packages system-wide, try apt install\n    python3-xyz, where xyz is the package you are trying to\n    install.\n    \n    If you wish to install a non-Debian-packaged Python package,\n    create a virtual environment using python3 -m venv path/to/venv.\n    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make\n    sure you have python3-full installed.\n    \n    If you wish to install a non-Debian packaged Python application,\n    it may be easiest to use pipx install xyz, which will manage a\n    virtual environment for you. Make sure you have pipx installed.\n    \n    See /usr/share/doc/python3.11/README.venv for more information.\n\nnote: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.\nhint: See PEP 668 for the detailed specification.\n"}

You should probably install python3-pexpect with apt instead of pip on Proxmox 8.

**Comment by cu** [comment]
Do you have the latest version? [The most recent commit](https://github.com/simoncaron/ansible-role-pve_acme/commit/1ad036b50735fdf6b7fbb08411f09c2398ad776c) seems to do exactly that...

**Comment by Jarige** [comment]
Right, that's a bit embarrassing. I've updated from 1.2.0 to 1.4.0 and it works now, thanks!

To anyone else who wants to evade the problem I ran into, this fixes it:
ansible-galaxy install simoncaron.pve_acme --force 

I never realized Ansible Galaxy does not automatically update the roles you've downloaded from it.

Thanks again!
